import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "StockFlow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <head>
              {/* เพิ่ม Material Icons */}
              <link
                  href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
                  rel="stylesheet"
              />
          </head>
          <body className="bg-gray-100 text-gray-800">
              {children}
          </body>
      </html>
  );
}